/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import harvestManagement.Helper;
import harvestManagement.HelperManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maxpo
 */
public class TableDialogHelper extends javax.swing.JDialog {
    
    public HelperManager helperManager;
    
    /**
     * Creates new form TableDialog
     */
    public TableDialogHelper(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        helperManager = new HelperManager();
        addRowToJTable();
    }

    public void addHelper(Helper helper)
    {  
        DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();
        
        Object rowData[] = new Object[5];
        
        rowData[0] = helper.getId();
            rowData[1] = helper.getFirstName();
            rowData[2] = helper.getLastName();
            rowData[3] = helper.getGender();
            rowData[4] = helper.getOrigin();
            modelHelper.addRow(rowData);
        
        helperManager.addHelper(helper);
        System.out.println(helperManager.getAllHelpers().toString());
    }
    
    public void addRowToJTable()
    {
        DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();
        ArrayList<Helper> localHelper = new ArrayList<Helper>();
        
        //demo content
        Helper helper01 = new Helper("Max","Mustermann","Male","GER");
        Helper helper02 = new Helper("Hans","Werner","Female","AUS");
        Helper helper03 = new Helper("Maria","Mülller","Divers","SWE");
        localHelper.add(helper01);
        localHelper.add(helper02);
        localHelper.add(helper03);
        
        Object rowData[] = new Object[5];
        
        for (int i=0; i < localHelper.size(); i++)
        {
            rowData[0] = localHelper.get(i).getId();
            rowData[1] = localHelper.get(i).getFirstName();
            rowData[2] = localHelper.get(i).getLastName();
            rowData[3] = localHelper.get(i).getGender();
            rowData[4] = localHelper.get(i).getOrigin();
            modelHelper.addRow(rowData);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableHelper = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textGender = new javax.swing.JTextField();
        textOrigin = new javax.swing.JTextField();
        buttonCreate = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableHelper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HelperID", "FirstName", "LastName", "Gender", "Origin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHelper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHelperMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHelper);

        jLabel1.setText("Welcome to the Helper Manager");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Gender:");

        jLabel5.setText("Origin:");

        textFirstName.setText("First Name");

        textLastName.setText("Last Name");

        textGender.setText("Gender");
        textGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textGenderActionPerformed(evt);
            }
        });

        textOrigin.setText("Origin");

        buttonCreate.setText("Create");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(183, 183, 183))
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textGender, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(textOrigin)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreate)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        
        int a = JOptionPane.showOptionDialog(this, "Are you sure you want to delete this Helper?", "Please confirm!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(a == 0)
        {
            DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();
            int i = tableHelper.getSelectedRow();
            if (i>=0)
            {
                modelHelper.removeRow(i);
                helperManager.deleteHelper(Integer.parseInt(modelHelper.getValueAt(i,1).toString()));
            }
            else
            {
                System.out.println("Delete Error!");
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void textGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textGenderActionPerformed

    }//GEN-LAST:event_textGenderActionPerformed

    private void tableHelperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHelperMouseClicked
        int i = tableHelper.getSelectedRow();
        DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();
        textFirstName.setText(modelHelper.getValueAt(i,1).toString());
        textLastName.setText(modelHelper.getValueAt(i,2).toString());
        textGender.setText(modelHelper.getValueAt(i,3).toString());
        textOrigin.setText(modelHelper.getValueAt(i,4).toString());
    }//GEN-LAST:event_tableHelperMouseClicked

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        //int i = tableHelper.getSelectedRow();
        //tableHelper.editCellAt(i, WIDTH);
        /*DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();
        if (textFirstName.getText().equals("")) //INPUT CONTROL
        {
            return;
        }
        else
        {
        modelHelper.setValueAt(textFirstName.getText(),i,1);
        }
        modelHelper.setValueAt(textLastName.getText(),i,2);
        modelHelper.setValueAt(textGender.getText(),i,3);
        modelHelper.setValueAt(textOrigin.getText(),i,4);
        
        Helper helper = new Helper (textFirstName.getText(),textLastName.getText(),textGender.getText(),textOrigin.getText());
        helperManager.updateHelper(Integer.parseInt(modelHelper.getValueAt(i,1).toString()), helper);
        */
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();
        
        Helper helper = new Helper (textFirstName.getText(),textLastName.getText(),textGender.getText(),textOrigin.getText());
        Object rowData[] = new Object[5];
        
        rowData[0] = helper.getId();
            rowData[1] = helper.getFirstName();
            rowData[2] = helper.getLastName();
            rowData[3] = helper.getGender();
            rowData[4] = helper.getOrigin();
            modelHelper.addRow(rowData);
        
        helperManager.addHelper(helper);
    }//GEN-LAST:event_buttonCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableDialogHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableDialogHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableDialogHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableDialogHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableDialogHelper dialog = new TableDialogHelper(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreate;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHelper;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textGender;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textOrigin;
    // End of variables declaration//GEN-END:variables
}
