/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import harvestManagement.BerryManager;
import harvestManagement.Berry;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maxpo
 */
public class TableDialogBerries extends javax.swing.JDialog {
    
    public BerryManager berryManager;
    
    /**
     * Creates new form TableDialogBerries
     */
    public TableDialogBerries(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        berryManager = new BerryManager();
        addRowToJTable();
    }

    public void addRowToJTable()
    {
        DefaultTableModel modelBerry = (DefaultTableModel) tableBerries.getModel();
        ArrayList<Berry> localBerry = new ArrayList<Berry>();
        
        //demo content
        Berry berry01 = new Berry("Strawberry",2.0,"Red","sweet");
        Berry berry02 = new Berry("Blackberry",1.0,"Dark Blue","sour");
        Berry berry03 = new Berry("Rass",2.0,"Male","GER");
        localBerry.add(berry01);
        localBerry.add(berry02);
        localBerry.add(berry03);
        
        Object rowData[] = new Object[5];
        
        for (int i=0; i < localBerry.size(); i++)
        {
            rowData[0] = localBerry.get(i).getBerryId();
            rowData[1] = localBerry.get(i).getSpecies();
            rowData[2] = localBerry.get(i).getWeight();
            rowData[3] = localBerry.get(i).getColor();
            rowData[4] = localBerry.get(i).getTaste();
            modelBerry.addRow(rowData);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textSpecies = new javax.swing.JTextField();
        textWeight = new javax.swing.JTextField();
        textColor = new javax.swing.JTextField();
        textTaste = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBerries = new javax.swing.JTable();
        buttonCreate = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Welcome to the Berry Manager");

        jLabel2.setText("Species:");

        jLabel3.setText("Weight:");

        jLabel4.setText("Color:");

        jLabel5.setText("Taste:");

        textSpecies.setText("Species");

        textWeight.setText("Weight");

        textColor.setText("Color");

        textTaste.setText("Taste");

        tableBerries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BerryID", "Species", "Weight", "Color", "Taste"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBerries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBerriesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBerries);

        buttonCreate.setText("Create");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textWeight))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textColor)
                            .addComponent(textTaste, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(textSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(textWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTaste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreate)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        int a = JOptionPane.showOptionDialog(this, "Are you sure you want to delete this Helper?", "Please confirm!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(a == 0)
        {
            DefaultTableModel modelBerries = (DefaultTableModel) tableBerries.getModel();
            int i = tableBerries.getSelectedRow();
            if (i>=0)
            {
                modelBerries.removeRow(i);
                berryManager.deleteBerry(Integer.parseInt(modelBerries.getValueAt(i,1).toString()));
            }
            else
            {
                System.out.println("Delete Error!");
            }
        }    
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void tableBerriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBerriesMouseClicked
        int i = tableBerries.getSelectedRow();
        DefaultTableModel modelBerries = (DefaultTableModel) tableBerries.getModel();
        textSpecies.setText(modelBerries.getValueAt(i,1).toString());
        textWeight.setText(modelBerries.getValueAt(i,2).toString()); //Does it work with double?
        textColor.setText(modelBerries.getValueAt(i,3).toString());
        textTaste.setText(modelBerries.getValueAt(i,4).toString());
    }//GEN-LAST:event_tableBerriesMouseClicked

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        int i = tableBerries.getSelectedRow();
        DefaultTableModel modelBerries = (DefaultTableModel) tableBerries.getModel();
        if (textSpecies.getText().equals("")) //INPUT CONTROL
        {
            return;
        }
        else
        {
        modelBerries.setValueAt(textSpecies.getText(),i,1);
        }
        modelBerries.setValueAt(textWeight.getText(),i,2);
        modelBerries.setValueAt(textColor.getText(),i,3);
        modelBerries.setValueAt(textTaste.getText(),i,4);
        
        Berry berry = new Berry (textSpecies.getText(),Double.valueOf(textWeight.getText()),textColor.getText(),textTaste.getText());
        berryManager.updateBerry(Integer.parseInt(modelBerries.getValueAt(i,1).toString()), berry);
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        DefaultTableModel modelBerries = (DefaultTableModel) tableBerries.getModel();
        
        Berry berry = new Berry (textSpecies.getText(),Double.valueOf(textWeight.getText()),textColor.getText(),textTaste.getText());
        Object rowData[] = new Object[5];
        
        rowData[0] = berry.getBerryId();
            rowData[1] = berry.getSpecies();
            rowData[2] = berry.getWeight();
            rowData[3] = berry.getColor();
            rowData[4] = berry.getTaste();
            modelBerries.addRow(rowData);
        
        berryManager.addBerry(berry);
    }//GEN-LAST:event_buttonCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableDialogBerries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableDialogBerries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableDialogBerries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableDialogBerries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableDialogBerries dialog = new TableDialogBerries(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreate;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableBerries;
    private javax.swing.JTextField textColor;
    private javax.swing.JTextField textSpecies;
    private javax.swing.JTextField textTaste;
    private javax.swing.JTextField textWeight;
    // End of variables declaration//GEN-END:variables
}
