/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import harvestManagement.BerryManager;
import harvestManagement.Helper;
import harvestManagement.HelperManager;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author maxpo
 */
public class TableDialogHelper1 extends javax.swing.JFrame implements TableModelListener {

    private HelperManager helperManager;
    private BerryManager berryManager;

    /**
     * Creates new form TableDialogHelper1 and executes addRowToJTable method.
     * Gets the table model and adds listener.
     */
    public TableDialogHelper1(HelperManager helperManager, BerryManager berryManager) {
        initComponents();
        this.helperManager = helperManager;
        this.berryManager = berryManager;
        addRowToJTable();
        tableHelper.getModel().addTableModelListener(this);
    }

    /**
     * Fills and adds rows with values from helper class via getter. Executes
     * method addHelper in Class HelperManager. Returns print out of all Helper.
     *
     * @param helper
     */
    public void addHelper(Helper helper) {
        DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();

        Object rowData[] = new Object[5];

        rowData[0] = helper.getId();
        rowData[1] = helper.getFirstName();
        rowData[2] = helper.getLastName();
        rowData[3] = helper.getGender();
        rowData[4] = helper.getOrigin();
        modelHelper.addRow(rowData);

        helperManager.addHelper(helper);
        System.out.println(helperManager.getAllHelpers().toString());
    }

    /**
     * Detects changes in table. If values are changed/beeing updated, new
     * values are set, transfered to class Helper Manager and printed out for
     * manual control.
     *
     * @param e
     */
    public void tableChanged(TableModelEvent e) {
        int row = e.getFirstRow();
        int column = e.getColumn();
        TableModel model = (TableModel) e.getSource();
        if (column < 0) {
            return;
        }
        Helper helper = null;

        for (int i = 0; i < helperManager.getAllHelpers().size(); i++) {
            if (helperManager.getAllHelpers().get(i).getId() == Integer.parseInt(model.getValueAt(row, 0).toString())) { //Control if helper Id equals value of column 0 (id column)
                helper = helperManager.getAllHelpers().get(i);
            }
        }

        if (helper != null) {
            helper.setFirstName(model.getValueAt(row, 1).toString());
            helper.setLastName(model.getValueAt(row, 2).toString());
            helper.setGender(model.getValueAt(row, 3).toString());
            helper.setOrigin(model.getValueAt(row, 4).toString());
            helperManager.updateHelper(Integer.parseInt(model.getValueAt(row, 0).toString()), helper);//new values to class HelperManager
            System.out.println(helperManager.getAllHelpers().toString());
        }
    }

    /**
     * Imports data from class HelperManager through getAllHelper method. Adds
     * data in row in modelHelper.
     */
    public void addRowToJTable() {
        DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();

        for (Helper helper : helperManager.getAllHelpers()) {

            Object rowData[] = new Object[5];
            rowData[0] = helper.getId();
            rowData[1] = helper.getFirstName();
            rowData[2] = helper.getLastName();
            rowData[3] = helper.getGender();
            rowData[4] = helper.getOrigin();

            modelHelper.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHelper = new javax.swing.JTable();
        buttonDelete = new javax.swing.JButton();
        buttonNew = new javax.swing.JButton();
        buttonMainMenu = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuHelper = new javax.swing.JMenuItem();
        menuBerries = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to the Helper Manager");

        tableHelper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HelperID", "FirstName", "LastName", "Gender", "Origin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHelper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHelperMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHelper);

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonNew.setText("New");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonMainMenu.setText("Back to main menu");
        buttonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainMenuActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit Programm");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Basic Data");

        menuHelper.setMnemonic('y');
        menuHelper.setText("Manage Helpers");
        menuHelper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelperActionPerformed(evt);
            }
        });
        editMenu.add(menuHelper);

        menuBerries.setMnemonic('p');
        menuBerries.setText("Manage Berries");
        menuBerries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBerriesActionPerformed(evt);
            }
        });
        editMenu.add(menuBerries);

        menuManage.setMnemonic('d');
        menuManage.setText("Manage...");
        menuManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageActionPerformed(evt);
            }
        });
        editMenu.add(menuManage);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        menuHelp.setMnemonic('c');
        menuHelp.setText("Help");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        helpMenu.add(menuHelp);

        menuAbout.setMnemonic('a');
        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        helpMenu.add(menuAbout);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonMainMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelete)
                    .addComponent(buttonNew)
                    .addComponent(buttonMainMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When table is selected by mouse click,...
     *
     * @param evt
     */
    private void tableHelperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHelperMouseClicked
    }//GEN-LAST:event_tableHelperMouseClicked

    /**
     * Selected row of table will be deleted, after confirmation of JOptionPane
     *
     * @param evt
     */
    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        int a = JOptionPane.showOptionDialog(this, "Are you sure you want to delete this Helper?", "Please confirm!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (a == 0) {
            DefaultTableModel modelHelper = (DefaultTableModel) tableHelper.getModel();
            int i = tableHelper.getSelectedRow();
            helperManager.deleteHelper(Integer.parseInt(modelHelper.getValueAt(i, 0).toString()));
            modelHelper.removeRow(i);
            System.out.println(helperManager.getAllHelpers().toString());
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    /**
     * Exit programm if menu bar/exit programm is beeing selected
     *
     * @param evt
     */
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * Closes window, back to main menu
     *
     * @param evt
     */
    private void buttonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainMenuActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buttonMainMenuActionPerformed

    /**
     * When HelperManager in menu bar is beeing selected JOptionPane opens
     * warnig
     *
     * @param evt
     */
    private void menuHelperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelperActionPerformed
        JOptionPane.showMessageDialog(this, "You are already in 'Helper Manager'", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menuHelperActionPerformed

    /**
     * Changes to BerryManager when selected in menu bar
     *
     * @param evt
     */
    private void menuBerriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBerriesActionPerformed
        setVisible(false);
        TableDialogBerries1 tdb = new TableDialogBerries1(berryManager, helperManager);
        tdb.setVisible(true);
    }//GEN-LAST:event_menuBerriesActionPerformed

    /**
     * When selected in menu bar, opens JOptionPane with text given in Testat
     *
     * @param evt
     */
    private void menuManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageActionPerformed
        JOptionPane.showMessageDialog(this, "Not yet implemented", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_menuManageActionPerformed

    /**
     * When selected in menu bar, opens help page (in this case JOptionPane
     * warning. Could be replaced)
     *
     * @param evt
     */
    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        JOptionPane.showMessageDialog(this, "Say Hello to my little Help", "Panic", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menuHelpActionPerformed

    /**
     * When selected in menu bar, opens about page (in this case JOptionPane
     * warning. Could be replaced)
     *
     * @param evt
     */
    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        JOptionPane.showMessageDialog(this, "Let's talk ABOUT", "About", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menuAboutActionPerformed

    /**
     * When selected in menu bar, opens new window to enter new data
     *
     * @param evt
     */
    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        FormNewHelper fnh = new FormNewHelper(this);
        fnh.setVisible(true);
    }//GEN-LAST:event_buttonNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonMainMenu;
    private javax.swing.JButton buttonNew;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBerries;
    private javax.swing.JMenuItem menuHelp;
    private javax.swing.JMenuItem menuHelper;
    private javax.swing.JMenuItem menuManage;
    private javax.swing.JTable tableHelper;
    // End of variables declaration//GEN-END:variables

}
